const NORMALIZE = "NORMALIZE";
const STANDARIZE = "STANDARIZE";

const SCALE_TYPES = {
  NORMALIZE,
  STANDARIZE,
};

const REMOVE_USERNAMES = "REMOVE_USERNAMES";
const REMOVE_URLS = "REMOVE_URLS";
const REMOVE_PUNCTUATION_MARKS = "REMOVE_PUNCTUATION_MARKS";
const TEXT_TO_LOWERCASE = "TEXT_TO_LOWERCASE";
const REMOVE_SHORT_WORDS = "REMOVE_SHORT_WORDS";

const TRANSFORMATIONS = {
  REMOVE_USERNAMES,
  REMOVE_URLS,
  REMOVE_PUNCTUATION_MARKS,
  TEXT_TO_LOWERCASE,
  REMOVE_SHORT_WORDS,
};

const NAIVE = "NAIVE";
const DENSE = "DENSE";
const CONV1D = "CONV1D";
const LSTM = "LSTM";
const DENSE_LABEL = "DENSE_LABEL";
const CONV1D_LABEL = "CONV1D_LABEL";
const LSTM_LABEL = "LSTM_LABEL";

const ALGORITHMS = {
  NAIVE,
  DENSE,
  CONV1D,
  LSTM,
  DENSE_LABEL,
  CONV1D_LABEL,
  LSTM_LABEL,
};

module.exports = { SCALE_TYPES, TRANSFORMATIONS, ALGORITHMS };
