const NORMALIZE = "NORMALIZE";
const STANDARIZE = "STANDARIZE";

const SCALE_TYPES = {
  NORMALIZE,
  STANDARIZE,
};

const REMOVE_USERNAMES = "REMOVE_USERNAMES";
const REMOVE_URLS = "REMOVE_URLS";
const REMOVE_PUNCTUATION_MARKS = "REMOVE_PUNCTUATION_MARKS";
const TEXT_TO_LOWERCASE = "TEXT_TO_LOWERCASE";
const REMOVE_SHORT_WORDS = "REMOVE_SHORT_WORDS";

const TRANSFORMATIONS = {
  REMOVE_USERNAMES,
  REMOVE_URLS,
  REMOVE_PUNCTUATION_MARKS,
  TEXT_TO_LOWERCASE,
  REMOVE_SHORT_WORDS,
};

module.exports = { SCALE_TYPES, TRANSFORMATIONS };
